### ISSUE TITLE
RabbitMQ configuration does not work (4.4.x)

### ISSUE THREAD

**Issue by vincnetas** [mautic/mautic#12020]
### Mautic Version

4.4.x series

### PHP version

7.4.33

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Same problem as described in issue https://github.com/mautic/mautic/issues/10378 (closed by bot)
@RCheesley was asking if  someone can test on 4.x
@vicampuzano relied that 4.x is having this issue
3 months no activity, issue closed. 

Could there be a workaround for this? 

Relates issues 
https://github.com/mautic/mautic/issues/11106
https://github.com/mautic/mautic/issues/9284

Copy of description:
This is what we are seeing -

sudo php bin/console mautic:queue:process --env=prod -i page_hit

In Container.php line 348:

You have requested a non-existent service "old_sound_rabbit_mq.mautic_consumer".

### How can we reproduce this issue?

Step 1: Install Mautic V4.4.6 (docker)
Step 2: Set up SMTP setting for email via any provider
Step 3: Enable Queue functionality (local.php file variables from https://docs.mautic.org/en/queue)

	'queue_protocol' => 'rabbitmq',
	'rabbitmq_host' => 'rabbit',
	'rabbitmq_port' => '5672',
	'rabbitmq_vhost' => '/',
	'rabbitmq_user' => 'guest',
	'rabbitmq_password' => 'guest',	
	'rabbitmq_idle_timeout' => 0,
	'rabbitmq_idle_timeout_exit_code' => 0,

Step 4: Run console command `./console mautic:queue:process -i page_hit`

### Relevant log output

```shell
root@f0aadb23eb16:/var/www/html/bin# ./console mautic:queue:process -i page_hit

In Container.php line 289:

  You have requested a non-existent service "old_sound_rabbit_mq.mautic_consumer".
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by vincnetas** [comment]
Ok, after trying to reproduce this on clean environment i managed to make this run.
I assume that there were some things cached with incorrect configuration.

So for anyone from the future this is my docker-compose :

```
version: "3"

services:
  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
  database:
    image: powertic/percona-docker
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=""
  mautic:
    container_name: mautic
    image: mautic/mautic:v4-apache
    environment:
      - MAUTIC_DB_HOST=database
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=mypassword
      - MAUTIC_DB_NAME=mautic4
      - MAUTIC_CONFIG_QUEUE_PROTOCOL=rabbitmq
      - MAUTIC_CONFIG_RABBITMQ_HOST=rabbit
    restart: always
    ports:
      - "8880:80"
```

Then in terminal 
```
docker-compose up -d
docker exec -it mautic /var/www/html/bin/console mautic:queue:process -i page_hit
```

In browser go to [http://localhost:8080http://localhost:8080/#/queues](http://localhost:8080/#/queues) you should see empty page_hit queue
