### ISSUE TITLE
[Focus Item] Preview: Custom CSS broken because of encoded line breaks

### ISSUE THREAD

**Issue by putzwasser** [mautic/mautic#12343]
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

If you try to customize the CSS for a focus item, you can't use the preview. This is because line breaks get encoded to `&#13;&#10;`

The code shipped in production is fine, but it is annoying, nevertheless. I'd create a PR, because it's probably only one line of code that needs to be changed, but I'm not familiar with the Mautic code.

### How can we reproduce this issue?

1. Create a focus item
2. Add custom CSS with line breaks
```css
#mauticform_myform_focus_myhoneytrap {display: none}

#mauticform_input_myform_focus_submit {
margin-top: 2rem
}

#mauticform_input_myform_focus_leadtext * {
margin-bottom: 1.5rem
}
```
3. The inspect the rendered preview html and the `<style>` tag: You'll get something similar to:
```html
<style scoped="">
    #mauticform_myform_focus_myhoneytrap {display: none}&#13;&#10;&#13;&#10;#mauticform_input_myform_focus_submit {&#13;&#10;margin-top: 2rem&#13;&#10;}&#13;&#10;&#13;&#10;#mauticform_input_anmeldungdoikampagne_focus_leittext * {&#13;&#10;margin-bottom: 1.5rem&#13;&#10;}    </style>
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct
