### ISSUE TITLE
My contacts disappeared after restarting services

### ISSUE THREAD

**Issue by mostafasolati** [mautic/mautic#14042]
### Mautic Version

5.0.x series

### Way of installing

I'm using a Docker image from https://hub.docker.com/r/mautic/mautic

### PHP version

8.1.28

### What happened?

I use Mautic inside docker, but after restarting my services half of my contacts disappeared. (to be precise today's leads, I have yesterday's in the dashboard) there are plenty of leads in the leads table but none of them have names and emails. please help me I paid a lot for those leads :(

This is my docker-compose file:

```
services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mypassword
    volumes:
      - ~/mysite/data/mariadb:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  mautic:
    image: docker.arvancloud.ir/mautic/mautic:5-apache
    restart: always
    ports:
      - "8090:80"
    environment:
      - MAUTIC_DB_HOST=mariadb
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=mypassword
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_RUN_CRON_JOBS=true
    volumes:
        - ~/mysite/data/mautic/config:/var/www/html/config
        - ~/mysite/data/mautic/media:/var/www/html/docroot/media
        - ./mautic-cron-jobs.sh:/etc/cron.d/mautic-cron-jobs
    depends_on:
      - mariadb
    networks:
      - mynetwork


  mautic_cron:
    image: docker.arvancloud.ir/mautic/mautic:5-apache
    restart: always
    volumes:
        - ~/mysite/data/mautic/config:/var/www/html/config
    environment:
      - MAUTIC_DB_HOST=mariadb
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=mypassword
      - MAUTIC_DB_NAME=mautic
      - DOCKER_MAUTIC_ROLE=mautic_cron
    depends_on:
      - mariadb
      - mautic
    networks:
      - mynetwork


  website:
    build:
      context: ./src/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ~/mysite/data/website/images:/app/images
      - ~/mysite/data/website/logs:/app/logs
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=mypassword
      - DB_DATABASE=mydb

    depends_on:
      - mariadb
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:r
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridges

```
### How can we reproduce this issue?

Step 1: use this dockercompose to bring up services and after inserting some data try to restart and rebuild them

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>
