### ISSUE TITLE
Not Found /saml/metadata.xml

### ISSUE THREAD

**Issue by YuanZhencai** [mautic/mautic#9700]
[//]: # ( Invisible comment:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Not Found /saml/metadata.xml

When I visit `mymautic.com/saml/metadata.xml`, it's display `404 Not Found`

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.1.33
| Browser | chrome 88.0.4324.150

### Steps to reproduce
1. Run mautic with docker-compose
```
version: '2'

services:

  mauticdb:
    image: percona/percona-server:5.7
    container_name: mauticdb
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysecret
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

  mautic:
    image: mautic/mautic
    container_name: mautic
    links:
      - mauticdb:mysql
    depends_on:
      - mauticdb
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html
    environment:
      - MAUTIC_DB_HOST=mauticdb
      - MYSQL_PORT_3306_TCP=3306
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=mysecret
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_RUN_CRON_JOBS=true
      - PHP_MAX_UPLOAD=30M
```

2. Visit `localhost/saml/metadata.xml`, display 404 not found

![image](https://user-images.githubusercontent.com/4961592/108580151-30a5de80-7365-11eb-8550-7b208b8e419f.png)

### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )
